api_version = "2025-01"
[[extensions]]
type = "ui_extension"
name = "RTL Checkout"
handle = "rtl-checkout"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"
