import type { AccountLabels, OrderStatusLabel } from "./types";

/**
 * Default customer account labels per locale.
 * Covers English (en), Arabic (ar), Hebrew (he), and Farsi (fa).
 */
const ACCOUNT_LABELS: Record<string, AccountLabels> = {
  en: {
    login: {
      email: "Email",
      password: "Password",
      signIn: "Sign in",
      forgotPassword: "Forgot password?",
      rememberMe: "Remember me",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
    },
    registration: {
      createAccount: "Create account",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      acceptTerms: "I accept the terms and conditions",
      alreadyHaveAccount: "Already have an account?",
      signIn: "Sign in",
    },
    passwordReset: {
      resetPassword: "Reset password",
      enterEmail: "Enter your email address",
      sendResetLink: "Send reset link",
      backToLogin: "Back to login",
      newPassword: "New password",
      confirmNewPassword: "Confirm new password",
      passwordUpdated: "Your password has been updated",
    },
    accountDetails: {
      myAccount: "My account",
      personalInfo: "Personal information",
      editProfile: "Edit profile",
      changePassword: "Change password",
      currentPassword: "Current password",
      saveChanges: "Save changes",
      accountUpdated: "Account updated successfully",
    },
    orderHistory: {
      orderHistory: "Order history",
      orderNumber: "Order number",
      orderDate: "Date",
      orderStatus: "Status",
      orderTotal: "Total",
      viewDetails: "View details",
      trackOrder: "Track order",
      noOrders: "You have no orders yet",
      reorder: "Reorder",
    },
    addressBook: {
      addressBook: "Address book",
      addAddress: "Add address",
      editAddress: "Edit address",
      deleteAddress: "Delete address",
      defaultAddress: "Default address",
      setAsDefault: "Set as default",
      noAddresses: "You have no saved addresses",
      firstName: "First name",
      lastName: "Last name",
      company: "Company",
      address1: "Address line 1",
      address2: "Address line 2",
      city: "City",
      country: "Country",
      province: "Province / State",
      postalCode: "Postal code",
      phone: "Phone",
    },
  },
  ar: {
    login: {
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      signIn: "تسجيل الدخول",
      forgotPassword: "نسيت كلمة المرور؟",
      rememberMe: "تذكرني",
      noAccount: "ليس لديك حساب؟",
      createAccount: "إنشاء حساب",
    },
    registration: {
      createAccount: "إنشاء حساب",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      acceptTerms: "أوافق على الشروط والأحكام",
      alreadyHaveAccount: "لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
    },
    passwordReset: {
      resetPassword: "إعادة تعيين كلمة المرور",
      enterEmail: "أدخل بريدك الإلكتروني",
      sendResetLink: "إرسال رابط إعادة التعيين",
      backToLogin: "العودة لتسجيل الدخول",
      newPassword: "كلمة المرور الجديدة",
      confirmNewPassword: "تأكيد كلمة المرور الجديدة",
      passwordUpdated: "تم تحديث كلمة المرور بنجاح",
    },
    accountDetails: {
      myAccount: "حسابي",
      personalInfo: "المعلومات الشخصية",
      editProfile: "تعديل الملف الشخصي",
      changePassword: "تغيير كلمة المرور",
      currentPassword: "كلمة المرور الحالية",
      saveChanges: "حفظ التغييرات",
      accountUpdated: "تم تحديث الحساب بنجاح",
    },
    orderHistory: {
      orderHistory: "سجل الطلبات",
      orderNumber: "رقم الطلب",
      orderDate: "التاريخ",
      orderStatus: "الحالة",
      orderTotal: "الإجمالي",
      viewDetails: "عرض التفاصيل",
      trackOrder: "تتبع الطلب",
      noOrders: "لا توجد طلبات بعد",
      reorder: "إعادة الطلب",
    },
    addressBook: {
      addressBook: "دفتر العناوين",
      addAddress: "إضافة عنوان",
      editAddress: "تعديل العنوان",
      deleteAddress: "حذف العنوان",
      defaultAddress: "العنوان الافتراضي",
      setAsDefault: "تعيين كافتراضي",
      noAddresses: "لا توجد عناوين محفوظة",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      company: "الشركة",
      address1: "سطر العنوان 1",
      address2: "سطر العنوان 2",
      city: "المدينة",
      country: "الدولة",
      province: "المحافظة / الولاية",
      postalCode: "الرمز البريدي",
      phone: "الهاتف",
    },
  },
  he: {
    login: {
      email: "אימייל",
      password: "סיסמה",
      signIn: "התחברות",
      forgotPassword: "שכחת סיסמה?",
      rememberMe: "זכור אותי",
      noAccount: "אין לך חשבון?",
      createAccount: "יצירת חשבון",
    },
    registration: {
      createAccount: "יצירת חשבון",
      firstName: "שם פרטי",
      lastName: "שם משפחה",
      email: "אימייל",
      password: "סיסמה",
      confirmPassword: "אישור סיסמה",
      acceptTerms: "אני מסכים/ה לתנאים וההגבלות",
      alreadyHaveAccount: "כבר יש לך חשבון?",
      signIn: "התחברות",
    },
    passwordReset: {
      resetPassword: "איפוס סיסמה",
      enterEmail: "הזן את כתובת האימייל שלך",
      sendResetLink: "שלח קישור לאיפוס",
      backToLogin: "חזרה להתחברות",
      newPassword: "סיסמה חדשה",
      confirmNewPassword: "אישור סיסמה חדשה",
      passwordUpdated: "הסיסמה עודכנה בהצלחה",
    },
    accountDetails: {
      myAccount: "החשבון שלי",
      personalInfo: "מידע אישי",
      editProfile: "עריכת פרופיל",
      changePassword: "שינוי סיסמה",
      currentPassword: "סיסמה נוכחית",
      saveChanges: "שמור שינויים",
      accountUpdated: "החשבון עודכן בהצלחה",
    },
    orderHistory: {
      orderHistory: "היסטוריית הזמנות",
      orderNumber: "מספר הזמנה",
      orderDate: "תאריך",
      orderStatus: "סטטוס",
      orderTotal: "סה״כ",
      viewDetails: "צפה בפרטים",
      trackOrder: "עקוב אחר הזמנה",
      noOrders: "אין לך הזמנות עדיין",
      reorder: "הזמן שוב",
    },
    addressBook: {
      addressBook: "פנקס כתובות",
      addAddress: "הוסף כתובת",
      editAddress: "ערוך כתובת",
      deleteAddress: "מחק כתובת",
      defaultAddress: "כתובת ברירת מחדל",
      setAsDefault: "הגדר כברירת מחדל",
      noAddresses: "אין כתובות שמורות",
      firstName: "שם פרטי",
      lastName: "שם משפחה",
      company: "חברה",
      address1: "שורת כתובת 1",
      address2: "שורת כתובת 2",
      city: "עיר",
      country: "מדינה",
      province: "מחוז / מדינה",
      postalCode: "מיקוד",
      phone: "טלפון",
    },
  },
  fa: {
    login: {
      email: "ایمیل",
      password: "رمز عبور",
      signIn: "ورود",
      forgotPassword: "رمز عبور را فراموش کرده‌اید؟",
      rememberMe: "مرا به خاطر بسپار",
      noAccount: "حساب کاربری ندارید؟",
      createAccount: "ایجاد حساب",
    },
    registration: {
      createAccount: "ایجاد حساب",
      firstName: "نام",
      lastName: "نام خانوادگی",
      email: "ایمیل",
      password: "رمز عبور",
      confirmPassword: "تأیید رمز عبور",
      acceptTerms: "شرایط و ضوابط را می‌پذیرم",
      alreadyHaveAccount: "قبلاً حساب دارید؟",
      signIn: "ورود",
    },
    passwordReset: {
      resetPassword: "بازنشانی رمز عبور",
      enterEmail: "آدرس ایمیل خود را وارد کنید",
      sendResetLink: "ارسال لینک بازنشانی",
      backToLogin: "بازگشت به ورود",
      newPassword: "رمز عبور جدید",
      confirmNewPassword: "تأیید رمز عبور جدید",
      passwordUpdated: "رمز عبور شما با موفقیت بروزرسانی شد",
    },
    accountDetails: {
      myAccount: "حساب من",
      personalInfo: "اطلاعات شخصی",
      editProfile: "ویرایش پروفایل",
      changePassword: "تغییر رمز عبور",
      currentPassword: "رمز عبور فعلی",
      saveChanges: "ذخیره تغییرات",
      accountUpdated: "حساب با موفقیت بروزرسانی شد",
    },
    orderHistory: {
      orderHistory: "تاریخچه سفارشات",
      orderNumber: "شماره سفارش",
      orderDate: "تاریخ",
      orderStatus: "وضعیت",
      orderTotal: "مجموع",
      viewDetails: "مشاهده جزئیات",
      trackOrder: "پیگیری سفارش",
      noOrders: "هنوز سفارشی ندارید",
      reorder: "سفارش مجدد",
    },
    addressBook: {
      addressBook: "دفترچه آدرس",
      addAddress: "افزودن آدرس",
      editAddress: "ویرایش آدرس",
      deleteAddress: "حذف آدرس",
      defaultAddress: "آدرس پیش‌فرض",
      setAsDefault: "تنظیم به عنوان پیش‌فرض",
      noAddresses: "آدرس ذخیره‌شده‌ای ندارید",
      firstName: "نام",
      lastName: "نام خانوادگی",
      company: "شرکت",
      address1: "خط آدرس 1",
      address2: "خط آدرس 2",
      city: "شهر",
      country: "کشور",
      province: "استان / ایالت",
      postalCode: "کد پستی",
      phone: "تلفن",
    },
  },
};

const ORDER_STATUS_LABELS: Record<string, OrderStatusLabel[]> = {
  en: [
    { status: "pending", label: "Pending" },
    { status: "processing", label: "Processing" },
    { status: "shipped", label: "Shipped" },
    { status: "delivered", label: "Delivered" },
    { status: "cancelled", label: "Cancelled" },
    { status: "refunded", label: "Refunded" },
    { status: "returned", label: "Returned" },
  ],
  ar: [
    { status: "pending", label: "قيد الانتظار" },
    { status: "processing", label: "قيد المعالجة" },
    { status: "shipped", label: "تم الشحن" },
    { status: "delivered", label: "تم التوصيل" },
    { status: "cancelled", label: "ملغي" },
    { status: "refunded", label: "تم الاسترداد" },
    { status: "returned", label: "تم الإرجاع" },
  ],
  he: [
    { status: "pending", label: "ממתין" },
    { status: "processing", label: "בעיבוד" },
    { status: "shipped", label: "נשלח" },
    { status: "delivered", label: "נמסר" },
    { status: "cancelled", label: "בוטל" },
    { status: "refunded", label: "הוחזר כספית" },
    { status: "returned", label: "הוחזר" },
  ],
  fa: [
    { status: "pending", label: "در انتظار" },
    { status: "processing", label: "در حال پردازش" },
    { status: "shipped", label: "ارسال شده" },
    { status: "delivered", label: "تحویل داده شده" },
    { status: "cancelled", label: "لغو شده" },
    { status: "refunded", label: "بازپرداخت شده" },
    { status: "returned", label: "مرجوع شده" },
  ],
};

export function getAccountLabels(locale: string): AccountLabels {
  const base = locale.split("-")[0]?.toLowerCase() ?? "en";
  return ACCOUNT_LABELS[base] ?? ACCOUNT_LABELS["en"];
}

export function getOrderStatusLabels(locale: string): OrderStatusLabel[] {
  const base = locale.split("-")[0]?.toLowerCase() ?? "en";
  return ORDER_STATUS_LABELS[base] ?? ORDER_STATUS_LABELS["en"];
}

export function getOrderStatusLabel(locale: string, status: string): string {
  const labels = getOrderStatusLabels(locale);
  const match = labels.find((l) => l.status === status);
  return match?.label ?? status;
}
